alfablog/alfablog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_blog.urls')),
]

alfablog/data_blog/urls.py
from django.urls import path
from . import views

app_name = 'data_blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
]

alfablog/data_blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

alfablog/data_blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post



# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'blog/home.html', context) 

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

alfablog/data_blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Data Blog</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    </head>
    <body>
        <section class="section">
            <div class="container">
                <h1 class="title">Data Blog</h1>
            </div>
        </section>
    
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{% url 'data_blog:post_list' %}">
                        Home
                    </a>
                </div>
            </div>
        </nav>
    
        <section class="section">
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </section>
    
        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    &copy; 2023 Data Blog
                </p>
            </div>
        </footer>
    </body>
</html>

alfablog/data_blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">{{ post.title }}</p>
        </header>
        <div class="card-content">
            <div class="content">
                {{ post.content }}
                <br>
                <time datetime="{{ post.date_posted }}">Posted on {{ post.date_posted }}</time>
            </div>
        </div>
        <footer class="card-footer">
            <a href="{% url 'data_blog:post_list' %}" class="card-footer-item">Back to posts</a>
        </footer>
    </div>
{% endblock content %}

alfablog/data_blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <div class="card-content">
                <p class="title">{{ post.title }}</p>
                <p class="content">{{ post.content|truncatewords:30 }}</p>
                <time datetime="{{ post.date_posted }}">{{ post.date_posted }}</time>
                <a class="button is-link" href="{% url 'data_blog:post_detail' post.id %}">Read more</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}